package com.example.test1.repository;

import com.example.test1.Syain;
import com.example.test1.SyainExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SyainMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table syain
     *
     * @mbg.generated Tue Jan 04 14:31:41 JST 2022
     */
    long countByExample(SyainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table syain
     *
     * @mbg.generated Tue Jan 04 14:31:41 JST 2022
     */
    int deleteByExample(SyainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table syain
     *
     * @mbg.generated Tue Jan 04 14:31:41 JST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table syain
     *
     * @mbg.generated Tue Jan 04 14:31:41 JST 2022
     */
    int insert(Syain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table syain
     *
     * @mbg.generated Tue Jan 04 14:31:41 JST 2022
     */
    int insertSelective(Syain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table syain
     *
     * @mbg.generated Tue Jan 04 14:31:41 JST 2022
     */
    List<Syain> selectByExample(SyainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table syain
     *
     * @mbg.generated Tue Jan 04 14:31:41 JST 2022
     */
    Syain selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table syain
     *
     * @mbg.generated Tue Jan 04 14:31:41 JST 2022
     */
    int updateByExampleSelective(@Param("record") Syain record, @Param("example") SyainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table syain
     *
     * @mbg.generated Tue Jan 04 14:31:41 JST 2022
     */
    int updateByExample(@Param("record") Syain record, @Param("example") SyainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table syain
     *
     * @mbg.generated Tue Jan 04 14:31:41 JST 2022
     */
    int updateByPrimaryKeySelective(Syain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table syain
     *
     * @mbg.generated Tue Jan 04 14:31:41 JST 2022
     */
    int updateByPrimaryKey(Syain record);
}