package com.example.test1;

public class Syain {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column syain.id
     *
     * @mbg.generated Tue Jan 04 14:31:41 JST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column syain.name
     *
     * @mbg.generated Tue Jan 04 14:31:41 JST 2022
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column syain.romaji
     *
     * @mbg.generated Tue Jan 04 14:31:41 JST 2022
     */
    private String romaji;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column syain.id
     *
     * @return the value of syain.id
     *
     * @mbg.generated Tue Jan 04 14:31:41 JST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column syain.id
     *
     * @param id the value for syain.id
     *
     * @mbg.generated Tue Jan 04 14:31:41 JST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column syain.name
     *
     * @return the value of syain.name
     *
     * @mbg.generated Tue Jan 04 14:31:41 JST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column syain.name
     *
     * @param name the value for syain.name
     *
     * @mbg.generated Tue Jan 04 14:31:41 JST 2022
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column syain.romaji
     *
     * @return the value of syain.romaji
     *
     * @mbg.generated Tue Jan 04 14:31:41 JST 2022
     */
    public String getRomaji() {
        return romaji;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column syain.romaji
     *
     * @param romaji the value for syain.romaji
     *
     * @mbg.generated Tue Jan 04 14:31:41 JST 2022
     */
    public void setRomaji(String romaji) {
        this.romaji = romaji == null ? null : romaji.trim();
    }
}